// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using petProfile.Database;

#nullable disable

namespace petProfile.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250830123359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("petProfile.Model.Entities.Donation", b =>
                {
                    b.Property<Guid>("donation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("rescue_center_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("donation_id");

                    b.HasIndex("rescue_center_id");

                    b.HasIndex("user_id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("petProfile.Model.Entities.Pet", b =>
                {
                    b.Property<Guid>("pet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("energy_level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("gender")
                        .HasColumnType("bit");

                    b.Property<bool>("good_with_children")
                        .HasColumnType("bit");

                    b.Property<bool>("good_with_other_pets")
                        .HasColumnType("bit");

                    b.Property<bool>("is_adopted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("rescue_center_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("rescue_condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rescue_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("rescue_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rescued_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("spayed_neutered")
                        .HasColumnType("bit");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("vaccination_status")
                        .HasColumnType("bit");

                    b.Property<string>("weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pet_id");

                    b.HasIndex("rescue_center_id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("petProfile.Model.Entities.Report", b =>
                {
                    b.Property<Guid>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("pet_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("rescue_center_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("urgency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("report_id");

                    b.HasIndex("rescue_center_id");

                    b.HasIndex("user_id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("petProfile.Model.Entities.RescueCenter", b =>
                {
                    b.Property<Guid>("center_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("center_id");

                    b.ToTable("RescueCenters");
                });

            modelBuilder.Entity("petProfile.Model.Entities.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("petProfile.Model.Entities.Donation", b =>
                {
                    b.HasOne("petProfile.Model.Entities.RescueCenter", "RescueCenter")
                        .WithMany("Donations")
                        .HasForeignKey("rescue_center_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("petProfile.Model.Entities.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("petProfile.Model.Entities.Pet", b =>
                {
                    b.HasOne("petProfile.Model.Entities.RescueCenter", "RescueCenter")
                        .WithMany("Pets")
                        .HasForeignKey("rescue_center_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueCenter");
                });

            modelBuilder.Entity("petProfile.Model.Entities.Report", b =>
                {
                    b.HasOne("petProfile.Model.Entities.RescueCenter", "RescueCenter")
                        .WithMany("Reports")
                        .HasForeignKey("rescue_center_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("petProfile.Model.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RescueCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("petProfile.Model.Entities.RescueCenter", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Pets");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("petProfile.Model.Entities.User", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
